const val RELEASE_GROUP = "com.hendraanggrian"
const val RELEASE_ARTIFACT = "packaging-gradle-plugin"
const val RELEASE_VERSION = "0.2"
const val RELEASE_DESCRIPTION = "Start making native distributions for your JAR"
const val RELEASE_GITHUB = "https://github.com/hendraanggrian/$RELEASE_ARTIFACT"