const val RELEASE_USER = "hendraanggrian"
const val RELEASE_GROUP = "com.$RELEASE_USER"
const val RELEASE_ARTIFACT = "packr-gradle-plugin"
const val RELEASE_VERSION = "0.3"
const val RELEASE_DESC = "Start making native distributions for your JAR"
const val RELEASE_WEB = "https://github.com/$RELEASE_USER/$RELEASE_ARTIFACT"
