const val VERSION_GRADLE = "4.7"
const val VERSION_KOTLIN = "1.2.41"

internal const val VERSION_DOKKA = "0.9.16"
internal const val VERSION_PACKR = "2.1-SNAPSHOT"
internal const val VERSION_KTLINT = "0.23.1"
internal const val VERSION_SPEK = "1.1.5"
internal const val VERSION_JUNIT_PLATFORM = "1.0.0"
internal const val VERSION_BINTRAY_RELEASE = "0.8.1"
internal const val VERSION_GIT_PUBLISH = "0.3.3"